services:
    app:
        build: .
        volumes:
            - .:/var/www
            # Excluir dependencias instaladas
            - /var/www/vendor
            - /var/www/node_modules
        environment:
            APP_ENV: local
            APP_KEY: ${APP_KEY}
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: laravel_db
            DB_USERNAME: testPHP
            DB_PASSWORD: XXXC3F3D4
        networks:
            - backend
        depends_on:
            db:
                condition: service_healthy

    webserver:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - backend
        depends_on:
            - app

    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: laravel_db
            POSTGRES_USER: testPHP
            POSTGRES_PASSWORD: XXXC3F3D4
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            -   '5432:5432'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    pgdata:
